---
language: python
python:
  - "3.6"
services: docker

cache: pip

install:
  - pip3 install tox

script:
  - tox -e $(tox -a | paste -d , -s -)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications
