---
language: python
python:
  - "3.8"
services: docker

env:
  - MOLECULE_DISTRO=amazonlinux:1
  - MOLECULE_DISTRO=amazonlinux:2
  - MOLECULE_DISTRO=debian:stable
  - MOLECULE_DISTRO=debian:oldstable
  - MOLECULE_DISTRO=centos:7
  - MOLECULE_DISTRO=fedora:latest ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3
  - MOLECULE_DISTRO=ubuntu:focal
  - MOLECULE_DISTRO=ubuntu:bionic
  - MOLECULE_DISTRO=ubuntu:xenial
  - MOLECULE_DISTRO=ubuntu:trusty

install:
  - pip3 install ansible docker molecule testinfra yamllint ansible-lint prospector

script:
  - molecule test --all --parallel

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications
