---
- name: Converge
  hosts: all

  tasks:
    - name: Install aws cli
      import_role:
        name: ansible-aws_cli

    - name: Remove aws cli
      import_role:
        name: ansible-aws_cli
      vars:
        aws_cli_package_state: absent
