---
- name: Converge
  hosts: all

  tasks:
    - name: Apply ansible-aws_cli role
      import_role:
        name: ansible-aws_cli
      vars:
        profiles:
          - name: default
            region: us-east-2
            output: json
            aws_access_key_id: "{{ lookup('env','CI_AWS_ACCESS_KEY_ID') }}"
            aws_secret_access_key: "{{ lookup('env','CI_SECRET_ACCESS_KEY') }}"
          - name: cn
            region: cn-north-1
            output: text
            aws_access_key_id: AKIAIOSDNKOW7EXAMPLE
            aws_secret_access_key: wJalrXUtnFEMI/F3GXCLG/bPxRfiCYEXAMPLEKEY
          - name: sa
            region: sa-east-1
            output: json
            aws_access_key_id: AKIAIOSDNKOW73X4MPL3
            aws_secret_access_key: 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
          - name: no_aws_access_key_id
            aws_secret_access_key: wJalrXUtnFEMI/F3GXCLG/bPxRfiCY3XXMPL3K3Y
          - name: no_aws_secret_access_key
            aws_key_id: AKIAIOSDNKOW73XXMPL3
          - name: no_region
            output: test
          - name: no_output
            region: eu-central-1
